#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

set -e
set -v
set -u
set -x

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -f ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

# Map caps lock to ctrl
setxkbmap -option ctrl:nocaps
# Set awesome english keyboard layout
setxkbmap -layout us altgr-intl

# Start ssh-agent and add my keys
# export SSH_ASKPASS
export SSH_ASKPASS=/usr/lib/seahorse/seahorse-ssh-askpass
eval $(ssh-agent)
[ -e ~/.ssh/id_rsa ] && ssh-add -c ~/.ssh/id_rsa
[ -e ~/.ssh/anypoint.mulesoft.com.key ] && ssh-add ~/.ssh/anypoint.mulesoft.com.key
[ -e ~/.ssh/vpn/exchange-platform-dev.pem ] && ssh-add ~/.ssh/vpn/exchange-platform-dev.pem
[ -e ~/.ssh/vpn/exchange-platform-qa.pem ] && ssh-add ~/.ssh/vpn/exchange-platform-qa.pem

session=${1:-xmonad}
case $session in
    xmonad)
        # Turn off Touchpad
        xinput --disable 'ETPS/2 Elantech Touchpad'
        # Start urxvt daemon
        urxvtd -q -f -o
        # Start xscreensaver daemon
        xscreensaver -no-splash &
        # Enable numlock on startup
        numlockx &
        # Start pulseaudio
        start-pulseaudio-x11
        # Start easystroke
        easystroke &

        # Set the cursor
        xsetroot -cursor_name left_ptr
        # Set Spanish keyboard layout
        setxkbmap -layout es
        # Set wallpaper
        feh --bg-fill "$HOME/Pictures/Wallpapers/current"
        # Start notification server (dunst)
        dunst &
        # Start status bar engine
        "$HOME/.config/lueng/lueng.sh" &
        # Start xcompmgr for transparency
        xcompmgr &

        # Start xmonad
        # Start dzen with its socket (doesn't work yet)
        #nc -k -l -U ${HOME}/.xmonad/log.soc | dzen2 -ta l -bg '#161616' -fn 'Terminus:size=8' -w 600 -e '' -dock &
        # Actually start xmonad
        exec xmonad ;;
    i3) exec i3 ;;
    gnome) exec gnome-session ;;
    kde) exec startkde ;;
    mate) exec mate-session ;;
    cinnamon) exec cinnamon-session ;;
    *) exec $1 ;;
esac

# ...or the Window Manager of your choice
